# Generated by Django 3.2.7 on 2021-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.TextField(choices=[('M', 'Money'), ('T', 'Todos'), ('R', 'Reminders'), ('W', 'Work'), ('D', 'Default')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
